=== Cblyt/meal_planner_backend/routes/Schemas/API/ProductsController/api-products-by-id.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "price": {
            "type": "string"
        },
        "amount": {
            "type": "string"
        },
        "units": {
            "type": "string"
        },
        "store": {
            "type": "string"
        }
    },
    "required": [
        "id",
        "name",
        "price",
        "amount",
        "units",
        "store"
    ]
}

=== Cblyt/meal_planner_backend/tests/postman_tests/get_product_by_name/response.json
[{"id":99,"name":"Onions yellow","price":"1.69","amount":"3","units":"lbs","store":"Aldi"},{"id":439,"name":"Onions yellow","price":"1.99","amount":"2","units":"lbs","store":"Trader Joe"},{"id":269,"name":"Onions yellow","price":"2.29","amount":"3","units":"lbs","store":"Kroger"},{"id":609,"name":"Onions yellow","price":"2.99","amount":"3","units":"lbs","store":"Publix"},{"id":779,"name":"Onions yellow","price":"3.48","amount":"3","units":"lbs","store":"Walmart"}]
